server:
  port: 8804

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址
      discovery:
        cluster-name: WH #集群名称
        namespace: 2419bcf6-6d8e-4400-aec5-9272602cf8f8 #devId
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
userserver:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule #优先选择统一集群然后随机
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
#eureka:
#  client:
#    serviceUrl:
#      # 注册
#      defaultZone: http://localhost:8801/eureka