server:
  port: 10010
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
      discovery:
        cluster-name: WH #集群名称
        namespace: 2419bcf6-6d8e-4400-aec5-9272602cf8f8 #devId
    gateway:
      routes:  # 网关路由配置
        - id: user-server
          uri: lb://userserver # 目标地址
          predicates: # 断言规则
          - Path=/api/user/** # 路径断言
        - id: blog-server
          uri: lb://blogserver # 目标地址
          predicates: # 断言规则
          - Path=/api/blog/** # 路径断言
        - id: game-server
          uri: lb://gameserver # 目标地址
          predicates: # 断言规则
          - Path=/api/game/** # 路径断言
        - id: point-server
          uri: lb://pointserver # 目标地址
          predicates: # 断言规则
          - Path=/api/point/** # 路径断言
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        '[/**]':
          allowedMethods:
            - "GET"
            - "POST"
            - "DELETE"
            - "PUT"
            - "OPTIONS"
          allowedHeaders: "*"
          allowCredentials: true # 允许cookied
          maxAge: 360000 # 有效期